# --- Maven coordinates (vanniktech publish) ---
GROUP=com.dfcruz.modulens
POM_ARTIFACT_ID=modulens
VERSION_NAME=1.0.0

POM_NAME=Modulens
POM_DESCRIPTION=ModuLens is a Gradle plugin for analysing the module dependency structure of Android projects.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/thedfcruz/ModuLens

POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/thedfcruz/ModuLens
POM_SCM_CONNECTION=scm:git:git://github.com/thedfcruz/ModuLens.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/thedfcruz/ModuLens.git

POM_DEVELOPER_ID=dfcruz
POM_DEVELOPER_NAME=Diogo Cruz
POM_DEVELOPER_URL=https://github.com/thedfcruz

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true